name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-wheel tox-gh-actions
        pip install numpy==1.19.5
        pip install Cython
        pip install scipy
        python setup.py build_ext --inplace
        python setup.py install
    - name: Test with tox
      run: tox
